### PR TITLE
fix: android-headless-talkback-accessibility

### LINKED ISSUE #77542: [Due for Payment 2026-04-10][$150] [A11y] Screen Reader: Sign in: The language dropdown is announced as disabled and cannot be activated
## Action Performed:
Prerequisite:
- the user is not signed in

1. Using Android TalkBack, open the Expensify app
2. Swipe to the language dropdown button in the footer
3. Note how the control is announced.
4. Try to activate the control by double tapping

## Expected Result:
The control should be announced without a disabled state and the screen reader user should be able to activate it by double tapping.

## Actual Result:
When a user attempts to focus on the dropdown, TalkBack announces the component's name and state: "[Language Name], button disabled." The component also does not respond to the double-tap gesture, rendering the language selection inaccessible.

Note: the button can be activated without enabled TalkBack.

## Area issue was found in:
Sign in

## Failed WCAG checkpoints
WCAG 4.1.2 Name, Role, Value
https://www.w3.org/WAI/WCAG22/Understanding/name-role-value

## User impact:
Providing role, state, and value information on all user interface components enables compatibility with assistive technology, such as screen readers, screen magnifiers, and speech recognition software, used by people with disabilities.

## Suggested resolution:
Remove the disabled state and ensure the control can be activated with an enabled screen reader.
https://reactnative.dev/docs/accessibility#accessibilitystate

## Environment:
Samsung Galaxy S24 Ultra - Android 14, Partner - Native (No mobile browser)

## Screenshots/Videos

Image

https://github.com/user-attachments/assets/ad83a619-a015-4448-8b13-2d77e26fe0ae

**Version Number:** Production
**Reproducible in staging?:** NA
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** No
**Logs:** https://stackoverflow.com/c/expensify/questions/4856  NA
**Notes/Photos/Videos:** Any additional supporting documentation  Yes
**Expensify/Expensify Issue URL:** https://platform.applause.com/company/12102/products/36628/community-issues/7005441
**Issue reported by:** NA
**Slack conversation:** NA
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~022009685274860295821</li>
        <li>Upwork Job ID: 2009685274860295821</li>
        <li>Last Price Increase: 2026-04-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

### PR DESCRIPTION
**Pull request by TaduJR**
Fixes https://github.com/Expensify/App/issues/77542

Demo:

https://github.com/user-attachments/assets/614b6303-4ec0-4958-89b3-b8c8b54a7328

### CODE REVIEW

**Comment by inimaga** [comment]
@TaduJR Please merge main into your branch to fix the GitHub validation errors?

File: src/index.js [hunk 1]
```diff
@@ -579,16 +580,41 @@ export default class RNPickerSelect extends PureComponent {
...
+                return;
+            }
+            if (event.nativeEvent.actionName === 'activate') {
+                if (pickerRef && pickerRef.current && pickerRef.current.focus) {
+                    pickerRef.current.focus();
+                }
+            }
+        };
+
+        const accessibilityLabel = selectedItem.inputLabel || selectedItem.label;
```
Comment (eVoloshchak) [inline src/index.js]: Let's just pass whatever `accessibilityLabel` we pass to `RNPickerSelect` manually
```js
    <RNPickerSelect
      pickerProps={{
        accessibilityLabel: selectedItem.title,
      }}
    >
```

File: src/index.js [hunk 2]
```diff
@@ -579,16 +580,41 @@ export default class RNPickerSelect extends PureComponent {
...
                 testID="android_touchable_wrapper"
                 onPress={onOpen}
                 activeOpacity={1}
                 {...touchableWrapperProps}
+                accessible
+                accessibilityRole="combobox"
+                accessibilityLabel={accessibilityLabel}
+                accessibilityState={{ disabled }}
+                onAccessibilityAction={handleAccessibilityAction}
+                accessibilityActions={[{ name: 'activate' }]}
```
Comment (eVoloshchak) [inline src/index.js:609]: Should we add support for 'escape' action too?

**Comment by inimaga** [comment]
@TaduJR Please can we get some movement on this.

**Comment by TaduJR** [comment]
Hey @inimaga 

Very sorry for the delay 🙏

I was having some deploy blockers recently. Will surely handle it tomorrow.

Thanks for the bump!

File: src/index.js (hunk 2 above)
Comment (TaduJR) [reply src/index.js:609]: The iOS does not have this functionality, so adding for Android would make it inconsistent IMO. But if it's need we can do a separate follow-up PR.

File: src/index.js (hunk 1 above)
Comment (TaduJR) [reply src/index.js]: Done

**Comment by TaduJR** [comment]
@codex review

**Comment by TaduJR** [comment]
> To use Codex here, [create a Codex account and connect to github](https://chatgpt.com/codex/settings/connectors).

Oh, forgot codex is not install on this fork 😅

File: src/index.js (hunk 2 above)
Comment (eVoloshchak) [reply src/index.js:609]: @TaduJR, it's the other way around, iOS does support it, Android doesn't. Let's add it here

> so adding for Android would make it inconsistent IMO

But that still stands true, how do we close the picker on Android? Is it the 'collapse' action?

Comment (TaduJR) [reply src/index.js:609]: For iOS, yes - we could add 'escape' action to the Modal wrapper so VoiceOver users can dismiss with two-finger scrub (will call `togglePicker(true)`).

For Android, 'collapse' isn't the right action because when the native Picker opens, it's a system dialog that takes focus away from our wrapper. The `accessibilityActions` aren't reachable while the dialog is open. The system dialog handles its own dismissal via back button/gesture. So No additional action needed on our side.

**Review by eVoloshchak — APPROVED** [review]
LGTM!

**Comment by inimaga** [comment]
@TaduJR Could we merge main of the forked repo in here as considered [here](https://github.com/Expensify/App/issues/77542#issuecomment-3848723055)?

**Comment by inimaga** [comment]
Bump @TaduJR let's get this moving please

**Comment by TaduJR** [comment]
> @TaduJR Could we merge main of the forked repo in here as considered https://github.com/Expensify/App/issues/77542#issuecomment-3848723055?

Hi @inimaga 

Sorry for the delay.

I think we can consider that after merge this one, because this PR only focuses on addressing the specific issue, and merging with main here might make the diffs large and hard to review.

We could dedicate another PR for it.

WDYT?

**Review by inimaga — APPROVED** [review]
